### ISSUE TITLE
Typo in Chapter09/linux_time_01.cpp

### ISSUE THREAD

**Issue by rioj7** [PacktPublishing/C-System-Programming-Cookbook#1]
https://github.com/PacktPublishing/C-System-Programming-Cookbook/blob/master/Chapter09/linux_time_01.cpp

It doesn't matter where you put the `'` characters but it is better to group by 3
100'000'0000 == 1'000'000'000

**Comment by Kasper77** [comment]
thanks for your comment. 
Representing the number as you do will "make me think" about what number it is. If you look at the number on the right you almost immediately say: 1 billion, right? 
readability is one of the most important aspects when writing code (among others, of course).

**Comment by Kasper77** [comment]
absolutely agree. "Don't make me think" principle! 
thanks
